spring:
  application:
    name: core-processor
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/modula}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}


  kafka:
    bootstrap-servers: ${KAFKA-BROKERS:host.docker.internal:29092}
    listener:
      ack-mode: record
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.modula.coreprocessor.configuration.DltMessageSerializer
      retries: 3
    consumer:
      autoOffsetReset: earliest
      keyDeserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      valueDeserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer


kafka:
  topics:
    workflow-executor-topic: exec-topic


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

feign:
  clients:
    core-builder:
      url: ${CORE_BUILDER_CLIENT_URL:http://localhost:8090/}
